export const SET_LOADING = 'SET_LOADING';
export const RESET_STATE = 'RESET_STATE';

// Book
export const SET_FILTERS = 'SET_FILTERS';
export const GET_BOOKS = 'GET_BOOKS';
export const GET_MY_BOOKS = 'GET_MY_BOOKS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_BOOK = 'GET_BOOK';
export const ADD_BOOK = 'ADD_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';
export const EDIT_BOOK = 'EDIT_BOOK';
export const ERROR_BOOK = 'ERROR_BOOK';
export const GET_CATEGORY = 'GET_CATEGORY';
export const CREATE_REQUEST = 'CREATE_REQUEST';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const GET_MY_REQUESTS = 'GET_MY_REQUESTS';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const GET_MY_TRANSACTIONS = 'GET_MY_TRANSACTIONS';
export const GET_TRANSACTION = 'GET_TRANSACTION';
export const CHANGE_TRANSACTION_STATUS = 'CHANGE_TRANSACTION_STATUS';

// Auth
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESEND_EMAIL = 'RESEND_EMAIL';
export const CONFIRM_EMAIL = 'CONFIRM_EMAIL';
export const AUTH_FAIL = 'AUTH_FAIL';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const UPDATE_FAIL = 'UPDATE_FAIL';
export const ERROR_PROFILE = 'ERROR_PROFILE';
